### ISSUE TITLE
User wants to have a Stage Profile

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#116]
This issue assumes placeholders for the data.  Once SSO is available real data will incorporated and this work will be handled in another issue.

- [x] Stage cannot be accessed without being on the corporate network using a smartcard.  Once authenticated through the Users profile is accessible
- [x] The Profile will display all information passed by corporate (profile picture, first name, last name, emai).
- [x] Profile view will eventually (`show Coming Soon!`) show you all the Projects your a part, projects contribution distribution, and your Bookmarks.
- [x] Profile view will eventually (`grey and disabled`) allow the users to Create a Project from their profile.

**Comment by herrjosua** [comment]
@camelspeed  Since the Profile view does not have any content besides the avatar, should we just remove the item from the dropdown until we have more content? @btrayn

**Comment by herrjosua** [comment]
Basic layout has been completed. Waiting for SSO to be completed to finish this story.
