### ISSUE TITLE
Links to What's New from the User Menu

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#122]
Users should be able to see each release's enhancements.  We will store this on Enterprise Github so the link will reference that.

**Comment by herrjosua** [comment]
Placement of the `Release Notes` in the footer. Will also post in the `product-design` channel

![image](https://cloud.githubusercontent.com/assets/1341786/19276183/95e6ba6c-8fa3-11e6-994a-9f4a90f2cb71.png)

**Comment by btrayn** [comment]
Screenshot showing 'User Guide' link in user dropdown menu:
<img width="336" alt="screen shot 2016-10-11 at 11 09 48 am" src="https://cloud.githubusercontent.com/assets/17861032/19276215/abc8ce88-8fa3-11e6-9206-4774f315c280.png">

**Comment by herrjosua** [comment]
Screenshot of the `What's New` icon within the profile dropdown.

![screen shot 2016-10-12 at 10 03 05](https://cloud.githubusercontent.com/assets/1341786/19313252/d96e8aec-9063-11e6-90f4-e9b579cd805b.png)

**Comment by camelspeed** [comment]
@herrjosua technically there is no User Guide yet and  when one is available it should be a clear option.  This issue will need to be split otherwise it is incomplete.

**Comment by herrjosua** [comment]
`What's New` link has been added. Closing this issue.
