### ISSUE TITLE
Notify the User if they are Not using Google Chrome or Firefox

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#145]
Stage is optimized for the latest Chrome and then Firefox builds.  In Firefox we know our animation has issues (need to fix that soon) but at least you get in and then all else works fine.

We are starting to get help tickets saying that Stage is not working and all the users that do complain are using IE.

The system should detect the client browser being using and if it is not Chrome or Firefox then to provide the user with a message that Stage is optimized for those 2 browsers and to offer them the download links and to suggest the IE support is next on the roadmap.  The message should indicate what browser they are using too for clarity.

I'd like to see the mockup of the message and where it is placed before implementing.  This detection and interaction should be the first thing that occurs but also all URLs should do detection too in the event of a bookmark.

If IE is detected then can we simply route them to the main view and bypass the animation?  What does the rest of the app look like in IE?   If it is distorted beyond all recognition then we shouldn't help them in.  If it is decent with a few oddities but fully featured then ok but the message saying NOT optimized for IE should be understood.

So there are about 3-4 things here.  Let's take it iteratively.

**Comment by camelspeed** [comment]
@onetrickwolf @herrjosua Should we be saying it's optimized for Chrome AND Firefox?  Right now I only see it mentioning Chrome when I tried to use Safari.

**Comment by herrjosua** [comment]
Notification banner has been added. Closing this issue.
