### ISSUE TITLE
Design a Stage About View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#147]
Design an About viewe for Stage that helps introduce/frame/put in context what Stage is and is not.  We can talk about what content to provide but it should answer the typical questions: What, Why, How, Who and How to engage with the team.

 I would like the design to approach something like the suggestions below.

> http://nautil.us/  (I like the Curtain Raising effect. Plays well with the Stage theme.  My favorite but not sure how this plays out)
> http://www.boozallen.com
> http://ihub.bah.com
> https://boozallen.sharepoint.com/sites/innovation/dc-innovation-center 
> https://boozallen.sharepoint.com/sites/teams5/csquared

**Comment by herrjosua** [comment]
Proposed Design. Waiting for feedback.

![landing](https://cloud.githubusercontent.com/assets/1341786/20309495/2733103c-ab16-11e6-82da-a1a702145a66.png)
