### ISSUE TITLE
Disable Features That Are Not Implemented

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#172]
The following features will not be ready for Beta Release so disable them but keep them visible.  We keep them visible since it is an important concept and we disable them in order to prevent any negative perception of the application not work (and minimizing support requests)

- [x] Notication on header nav
- [x] Bookmark (User Menu, Project Details, Project Cards)
- [x] Share (Project Details, Project Cards)
- [x] Completely remove the Gameficiation ribbon from all Project Cards.

**Comment by camelspeed** [comment]
@herrjosua Bookmarks is still available from the User Profle Menu.  That needs to be adjusted too.

**Comment by herrjosua** [comment]
Ensured that `Bookmarks` from the User Dropdown has been disabled.

**Comment by herrjosua** [comment]
These item have been disabled. Closing this issue.
