### ISSUE TITLE
Auto-Suggest is not intuitive enough

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#174]
If you start typing `python` the suggestions are projects that do not have the word python in them.  If a user is not aware that we are suggesting the projects that have some relationship to their terms and may not contain their terms then it can cause confusion (it has since this is a user submitted issue).

How can we better control the user's experience and expectation of system behavior since this behavior is not inaccurate. Need more cues, more info, more something within the auto suggest feature?

**Comment by herrjosua** [comment]
UX Brothers' recommend removal of the Auto-suggest/complete drop-down feature until it is working correctly. Best UX practices states that if you have explicit provide instruction on how to use something, that it needs to be reconsidered.

**Comment by camelspeed** [comment]
Duplicate of #183
