### ISSUE TITLE
Display who has a Forked Project A in Project A's Details View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#184]
As part of the `Reuse` story we want to highlight `Who is Reusing Whom` by putting the Org/Project within the *reused* project's `Projects That Use Me`.

*Acceptance Criteria*
- [x] In Project X's `Projects That Use Me` on the Details View show all the projects that have forked Project X.  Display their `org/repo name` and make it open the project in another tab so the user stays on the project.
- [x] If there is no data to show then show the stock image  (currently a frown but another issue will track the stock image change)

**Comment by onetrickwolf** [comment]
@camelspeed #184 on the UI end is done @jthapliya and @natesol-code21 will be pushing their changes then I will submit a PR for merge on dev, this branch only works if you are pointing the datasource to @jthapliya sandbox at the moment

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
