### ISSUE TITLE
Move Health Statistics Below Dependencies on Project Details View

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#185]
Leadership wants Dependencies (namely to highlight Reuse) to show first and Health Statistics to come next.   This is the way we used to have it.

**Comment by herrjosua** [comment]
Per @camelspeed I reverted the order, back to `Health Statistics` above the `Dependencies`. Assuming no other changes this issue can be closed.

**Comment by camelspeed** [comment]
flipped back in #186.  We are not doing this change.
