### ISSUE TITLE
Update Frown Face for Projects That Use Us

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#187]
*Acceptance Criteria*

- [x] When there is no reuse data to show we want to show an encouraging and positive emoticon/icon so users are encouraged to update projects that they are reusing in some form.
- [x] Also change the message from "Make Me Reusable" to something to encourage the user to add their project as a consumer of this project, for example, "If you reuse this project then click here" or "Stage promotes Resuse so tell us if you're using this project". Modal pops up with instructions on how to Search or Manually enter if you do not exist.
- [x] Even when there is data we should have the "If you reuse this project..." feature present.

**Comment by herrjosua** [comment]
This has been completed. Changes are in branch 186. Once a PR is submitted for 186 this change be shown. I provided static HTML for @onetrickwolf. @onetrickwolf will need to convert the static HTML into Aurelia logic.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
