### ISSUE TITLE
The layout is broken for projects with large number of dependencies

### ISSUE THREAD

**Issue by jthapliya** [Project-Heimdall/home#190]
The layout of the dependencies section is broken for projects with large number of dependencies. In the project details page, click the more link for project "Cognition"

**Comment by herrjosua** [comment]
Issue has been fixed. @onetrickwolf Updated the logic to correctly flow the dependencies. Once issue #186 is finished this will need to be revisited as the layout is changing to a three column view compared to the current two column view.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
