### ISSUE TITLE
Fortify Link directs to the main page

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#191]
From the Project View page - clicking on the Fortify link takes the user to the Stage homepage

**Comment by camelspeed** [comment]
The link should be disabled and not clickable since this capability is not available.  I may direct us to complete remove it but for now make it not clickable per our standard way (no click mouse icon and not clickable).

**Comment by herrjosua** [comment]
@camelspeed I can make this link disabled, or I can remove it all together.

**Comment by herrjosua** [comment]
This link has been removed for now. Once Fortify is added the link will follow how the SonarQube link.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue. Link has been removed for the time being.
