### ISSUE TITLE
Bookmarks and Share Links should not be clickable

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#193]
From the project detail page, clicking the Bookmarks and Share Links direct the user to the main page.

**Comment by camelspeed** [comment]
Currently the features are not implemented so they should not be clickable.  The No Click indicator shows but still allows the user to click and navigate to the Home.  It is not yet determined if items we are NOT implementing should be removed altogether but until that is determined we will do this fix this way.

**Comment by herrjosua** [comment]
Verified that the `Bookmark` and `Share` buttons are disabled on DEV. Closing this issue.
