### ISSUE TITLE
Broken Link - Make Project Reusable on Project Details View

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#194]
From the Project Detail Page - Under Project Dependencies - the "Make Project Reusable" link directs users to the main page.

**Comment by camelspeed** [comment]
The link should be unclickable and grayed out.

**Comment by herrjosua** [comment]
This link has changed per issue home #186. This issue can be closed.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
