### ISSUE TITLE
Top Nav - Feedback Modal - Scroll Issue

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#204]
When on the Feedback Modal - mousing over the "Visit Stage Support" icon creates a scrollbar on the right.

![image](https://cloud.githubusercontent.com/assets/16209876/21943159/fc1e7e7a-d99d-11e6-83e2-f0fe7afc6df9.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
