### ISSUE TITLE
Top Nav - Search Bar

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#205]
As a user, I would like to see examples of what I can search for on the site in the Top Nav Search.

![image](https://cloud.githubusercontent.com/assets/16209876/21943091/c0ea3678-d99d-11e6-8972-2a4726c0997c.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
