### ISSUE TITLE
Change Name of Feedback Modal

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#206]
In order to keep people engaged, we should change the name of this modal to:

Get Engaged

![image](https://cloud.githubusercontent.com/assets/16209876/21943248/64cececa-d99e-11e6-9407-d7881a947804.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
