### ISSUE TITLE
Add Source of Statistics on Project Detail Page

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#207]
As a user, I want to know where these statistics come from.  Would be good to see the "Source Github" similar to the directory listing cards.

![image](https://cloud.githubusercontent.com/assets/16209876/21943318/c0de4470-d99e-11e6-9d2e-bd94c9f56260.png)

![image](https://cloud.githubusercontent.com/assets/16209876/21943380/ff89019c-d99e-11e6-9e6b-2bb76cfc54f8.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
