### ISSUE TITLE
Update Health Statistics Box

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#208]
A few things to update in the Health Statistics box:

1. Add back in the line between Quality and Security
2. Indicate Source of Data is SonarQube
3. Remove Fortify / Releasability -  Coming Soon (??  Do we want to do this? as it does not exist yet)
4. Can we repurpose the Build section since this is not yet available as an add to Extend Stage through Inner Sourcing?  (discussion needed)
5. Remove the View on Fortify Link as it makes it look like all security comes from Fortify when the SonarQube comes from SonarQube

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
