### ISSUE TITLE
Remove Complete Survey

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#209]
Remove the Complete Survey Button from the Feedback Modal.  

Change to "Get Involved"

Link coming to section of Wiki detailing this further.

![image](https://cloud.githubusercontent.com/assets/16209876/21943711/8842f1a4-d9a0-11e6-97c7-d96116e4b8a8.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
