### ISSUE TITLE
Change Link to say "Get Engaged"

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#210]
On the User Drop-Down Menu - Change this link to say "Get Engaged" to match the pop-up modal

![image](https://cloud.githubusercontent.com/assets/16209876/21943776/c61a284e-d9a0-11e6-823a-5b32bf2fdce4.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Text has been updated to `Get Involved`. @rebecca-allegar @camelspeed @skim012 Should the text be updated to what's in the story or should this issue be closed?

**Comment by herrjosua** [comment]
Issue has been verified in `PROD`. Closing this issue.
