### ISSUE TITLE
Profile Page Email Address Wrapping

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#212]
On the Profile Page, long email addresses spill out of the box.

![image](https://cloud.githubusercontent.com/assets/16209876/21944213/05612cbc-d9a3-11e6-93f1-f3534f75f5fb.png)

**Comment by herrjosua** [comment]
@rebecca-allegar How many characters is that email address?

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved. This will need to be double checked on this change has been pushed to DEV.

**Comment by herrjosua** [comment]
@jthapliya Since your email is long, can you check to see if this issue is resolved?

**Comment by herrjosua** [comment]
Issue has been verified in `PROD`. Closing this issue.
