### ISSUE TITLE
Log Out Link does not log out

### ISSUE THREAD

**Issue by rebecca-allegar** [Project-Heimdall/home#213]
Log Out Link does not log out.  Suspect with SSO this is not a possibility.  Suggest removing.

![image](https://cloud.githubusercontent.com/assets/16209876/21944397/03e4ea44-d9a4-11e6-93d3-085ff39fc865.png)

**Comment by herrjosua** [comment]
Resolved in #197. Once this a PR has been created this issue will be resolved.

**Comment by herrjosua** [comment]
Verified issue has been resolved on `PROD`. Closing this issue.
