### ISSUE TITLE
Bug - The "Watchers" stat is missing on the open repository.

### ISSUE THREAD

**Issue by farahfarahmand** [Project-Heimdall/home#53]
Environment: http://52.2.227.244/

Steps to reproduce:
1. Open Stage
2. Open a repository by clicking on its name from the Home page
3. Scroll down to the Key Stats

Expected Result: The "Watchers" stat should be displayed
Actual Result> "Watchers" stat is missing
[Missing Watchers stat.pptx](https://github.com/Project-Heimdall/home/files/387051/Missing.Watchers.stat.pptx)

**Comment by camelspeed** [comment]
we have not implemented paging yet so not a bug but just a visual.  I think you need to read through some of our stories and talk to get a grasp of what is considered implemented and how and perhaps help start creating documentation on our wiki to that affect.  We are in **startup** mode so continuously iterating and slicing features
