### ISSUE TITLE
Org and Code Language filters are dependent on each other.

### ISSUE THREAD

**Issue by farahfarahmand** [Project-Heimdall/home#56]
Environment: http://52.2.227.244/

Per "Filter by Org or Code Language or Both #66", the user should be able to filter by either of the filter types or by both.  However, if a user deselects all languages or all orgs, all view cards would disappear.  

Steps to reproduce:
1. Click either Popular or Explore - by default all checkboxes are checked
2. Deselect all checkboxes for Org and view that all view cards disappear although all the Language checkboxes are still checked
3. Select one or more Org filters and view that view cards reappear
4. Deselect all Org and Language filters and start checking only Language filters one by one and view that no view card displays unless an Org filter  is also checked

**Comment by camelspeed** [comment]
The intent is accurate.  Until we decide that unchecking all and having something checked elsewhere means something else this functionality is accurate.
