### ISSUE TITLE
The result set for when user selects a specific suggested value contains more results than the selected value.

### ISSUE THREAD

**Issue by farahfarahmand** [Project-Heimdall/home#62]
This can be clarified better with an example.

When user types in "spring" in the Search box, the app suggests values containing the word "spring" such as spring-amqp, spring-batch, spring-batch-admin, etc.  If user selects spring-amqp from the suggested values, the result set still shows/contains other projects with the word "spring" in their title or description.
![literal search](https://cloud.githubusercontent.com/assets/20666557/17340214/3dbe92dc-58bd-11e6-819c-8e34898b5c78.PNG)

**Comment by camelspeed** [comment]
This is not a bug.  Search is not performing literal exact matches.  Search is more complex (i.e. mathematical/statistical) so expecting to find just that and nothing else is not a correct assumption.  Now our model for interpretation may be weak but it is not clear that this is an outright error (most likely not).
