### ISSUE TITLE
Stars and Watchers counts for all projects are the same.

### ISSUE THREAD

**Issue by farahfarahmand** [Project-Heimdall/home#63]
For all projects in all views, the counts for Stars and Watchers are the same.

**Comment by camelspeed** [comment]
This is accurate per what is in Elastic Search. What is incorrect is how we are interpreting the data in GitHub.  See https://developer.github.com/changes/2012-09-05-watcher-api/ for clarification but basically we need to pull other data for Watchers (aka Subscribers)
