### ISSUE TITLE
Research SauceLabs for Testing

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#74]
Part of our overall testing strategy.  How can we leverage this?
https://saucelabs.com/open-source

**Comment by farahfarahmand** [comment]
Completed the task by researching the scope of manual testing with Sauce Labs. The extent of search included reading up the Sauce Labs documentations, creating a free trial account with Sauce Labs, practicing manual tests and viewing the test details, asking questions from Sauce Labs technical support, and finally creating a wiki page containing the result of search.
