### ISSUE TITLE
Research how we store and make use of Code, Config, and Build Files

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#76]
Need a data science perspective on:
- [x] How can we make use of Code, Config, and Build artifacts?
- [x] How do we process it to make use of it?

Focus on this Java Project to do the research.  This project use Maven for building (e.g. dependencies are here) and the build file is called `pom.xml`. This particular project is modularized so you'll find several `pom.xml` files withing child directories.

`https://github.com/boozallen/cognition`

**Comment by MelvinDunn** [comment]
Notes:

-How are we getting this information out of github? Yes, I understand that we're scraping it, but how?
-Will this be automated? We said we wanted this to be real time at one point.
-What are we doing about the subfolders? There's useful information in there.

-pom.xml - store these under their own variable in the database. they need to have their own stopwords and a different cleaning procedure (removing special characters, removing tags like "contributers" and "dependencies" that appear in every pom file). But yes, this is great information. These can be combined with the individual ReadMe it is associated with to make a better document.

-We should attempt to grab any readme's within sub folders and concatenate them by overall project. This goes for any pom.xml files within any subfolders.

-As for the code - we can try it out, but it may become a bit convoluted. Cleaning all of it might depend on the language. As we discussed yesterday, people's programming styles may be similar. There's also the fact that variables may be the same. However, the comments in the code would be very helpful. I would go ahead and bring the code in. 

Coherent Conclusion: 

Pom files should be brought in. They should have their own variable in elastic search. This is just for Java Pom, not other similar file types across other languages. I just want to have it in it's own column so I can clean the xml easily (BeautifulSoup or regex).

Try and concatenate similar files in the subfolders and store them in ES: ReadME's, pom.xml, and code

The code should also be brought in, but as a separate variable, and all the code in the subfolders should be concatenated beforehand. The comments in the code seem valuable. The specific functions from packages being stated is also valuable. Depending on the programming style, whether or not variable names are useful may vary. However, stopwords for the code may be a bit tricky. There's a slightly off chance of programmers using poor variables, like a,b,c,x, or y, and those poor variables being similar. Special characters will be taken out for the code, to get rid of operators. However, depending on the language (java and python), this might actually split some packages, variables, and objects. I might just keep the ".". Needs to actually be tested to make sure though.

I'll post to slack if anything else comes to mind.

**Comment by camelspeed** [comment]
Does the `how` part matter for your approach or are you concerned with having access to it?  We will incrementally figure this out but you can assume the data is in ES like now.  The end game is for the system to be updating ES near real-time or batch and automated.  Can you continue to operate like we are today?  What processing and storage requirements does your side have (I know search is not production but what is the roadmap to integrate with you?)  I need more insight into your side of the fence on how you all process or need to process data. I suppose another conversation with search folks is needed

**Comment by MelvinDunn** [comment]
The “how” part was merely of interest.

If the data is coming from ES in JSON format that is perfect.

I let the DEXi team know that you’re planning on automating this process, so we’ll be looking into that.

Ideally, I want the following for the updated information. I’ve yet to speak to Malachi and the DEXi team about this:


1.       Data is scraped and put into consistent format

a.       Scraped data should include subfolders, pom files, etc.

2.       Scraped Data is put into ES

a.       Scraped Data is reindexed, etc.

3.       DEXi accesses new data

4.       Data is cleaned, remodeled, and stored.

5.       Original DEXi endpoints for Similar Documents updated to reflect new information.

6.       Stage can access endpoints.

**Comment by camelspeed** [comment]
Pulling code from github across many repos to processing is non-trivial so we must have solid value add to take on such an endeavor.  Need our data science team to research before we engage in this thus putting it in the icebox until later.
