### ISSUE TITLE
User avatar not showing in Project Details Contributors card

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/home#93]
When a user (org or user) only has a Full Name and not a Username the avator does not show.  It shows a broken image.  Need to see if we can have the logic to pull this but something tells me that an Org (User of Type=Organization) is the problem.  Either way either we are able to pull this from Github and have it available or not; if not then we need to have a stock avatar (not random, maybe a no photo type thing).

**Comment by onetrickwolf** [comment]
Methods for grabbing icons are different for enterprise, need to adjust that too. Probably generate icon if one does not exist.

**Comment by onetrickwolf** [comment]
In the future may want to think about scraping avatars or moving the image stream to the API.

**Comment by onetrickwolf** [comment]
Made a fix that a default icon is at least loaded if the image fails, working on method to support loading for enterprise and if name is specified.
