### ISSUE TITLE
Explore View is missing count when no filters are active

### ISSUE THREAD

**Issue by herrjosua** [Project-Heimdall/home#97]
According to the design (see below) the `Explore` view should have a count of the number of repos on page load and after clear filters.

![stage ui v4-03](https://cloud.githubusercontent.com/assets/1341786/18205303/4ff0b544-70ef-11e6-8fd2-c0c81fdc0520.png)

What is currently on the development branch

![screen shot 2016-09-02 at 09 28 20](https://cloud.githubusercontent.com/assets/1341786/18205364/9d6d0f84-70ef-11e6-93ed-81a5785aa4cc.png)

**Comment by onetrickwolf** [comment]
I can fix this
